name: Automated Testing

on: 
  push:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 10 * * 1'  # Run at 10:00 AM every Monday

jobs:
  Selenium_test:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - name: Set up Selenium Grid
      run: |
        docker run -d -p 4444:4444 --name selenium-hub selenium/hub:4.1.1
        docker run -d --link selenium-hub:hub selenium/node-chrome:4.1.1

    - name: Build with Maven
      run: |
       mvn -B clean test
       
    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/surefire-reports
